pub const VALID_GAMES: [&str; 250] = [
    "Adventure",
    "Aquaria",
    "Blasphemous",
    "Bomb Rush Cyberfunk",
    "Bumper Stickers",
    "Castlevania - Circle of the Moon",
    "Castlevania 64",
    "Celeste 64",
    "ChecksFinder",
    "Civilization VI",
    "Dark Souls III",
    "DLCQuest",
    "Donkey Kong Country 3",
    "DOOM 1993",
    "DOOM II",
    "Factorio",
    "Faxanadu",
    "Final Fantasy",
    "Final Fantasy Mystic Quest",
    "A Hat in Time",
    "Heretic",
    "Hollow Knight",
    "Hylics 2",
    "Inscryption",
    "Jak and Daxter: The Precursor Legacy",
    "Kingdom Hearts",
    "Kingdom Hearts 2",
    "Kirby's Dream Land 3",
    "Landstalker - The Treasures of King Nole",
    "The Legend of Zelda",
    "Lingo",
    "A Link to the Past",
    "Links Awakening DX",
    "Lufia II Ancient Cave",
    "Mario & Luigi Superstar Saga",
    "Mega Man 2",
    "MegaMan Battle Network 3",
    "Meritous",
    "The Messenger",
    "Muse Dash",
    "Noita",
    "Ocarina of Time",
    "Overcooked! 2",
    "Pokemon Emerald",
    "Pokemon Red and Blue",
    "Raft",
    "Risk of Rain 2",
    "Saving Princess",
    "Secret of Evermore",
    "shapez",
    "Shivers",
    "A Short Hike",
    "SMZ3",
    "Sonic Adventure 2 Battle",
    "Starcraft 2",
    "Stardew Valley",
    "Subnautica",
    "Super Mario 64",
    "Super Mario Land 2",
    "Super Mario World",
    "Super Metroid",
    "Terraria",
    "Timespinner",
    "TUNIC",
    "Undertale",
    "VVVVVV",
    "Wargroove",
    "The Wind Waker",
    "The Witness",
    "Yacht Dice",
    "Yoshi's Island",
    "Yu-Gi-Oh! 2006",
    "Zillion",
    "A Difficult Game About Climbing",
    "A Link Between Worlds",
    "Against the Storm",
    "Air Delivery",
    "An Untitled Story",
    "Animal Well",
    "Anodyne",
    "Another Crab's Treasure",
    "APBingo",
    "Ape Escape 3",
    "Astalon",
    "Autopelago",
    "Balatro",
    "Banjo Tooie",
    "Battle for Bikini Bottom",
    "Bomberman Hero",
    "Brotato",
    "Candy Box 2",
    "Castlevania: Harmony of Dissonance",
    "Symphony of the Night",
    "Cave Story",
    "Cavern of Dreams",
    "Celeste Open World",
    "Chrono Trigger: Jets of Time",
    "Clique",
    "ClusterTruck",
    "Corn Kidz 64",
    "CrossCode",
    "Crystal Project",
    "Crystalis",
    "Dark Souls",
    "Dark Souls II",
    "Deep Rock Galactic",
    "Diddy Kong Racing",
    "Dome Keeper",
    "Donkey Kong Country 2",
    "Doronko Wanko",
    "Dragon Warrior",
    "Duke Nukem 3D",
    "Dungeon Clawler",
    "Earthbound",
    "Ender Lilies",
    "Final Fantasy 12 Open World",
    "Final Fantasy Tactics A2",
    "Final Fantasy Tactics Advance",
    "Final Fantasy VI",
    "Final Fantasy XII: Trial Mode",
    "Fire Emblem: The Sacred Stones (FE8)",
    "FNAF World",
    "Gauntlet Legends",
    "Getting Over It with Bennett Foddy",
    "Golden Sun The Lost Age",
    "Grim Dawn",
    "Guild Wars 2",
    "Hammerwatch",
    "Hatsune Miku: Project Diva Mega Mix+",
    "Here comes Niko!",
    "Iji",
    "Isles of the Sea and Sky",
    "Ittle Dew 2+",
    "Jak and Daxter",
    "Jigsaw",
    "JSPaint",
    "Kabuto Park DEMO",
    "Keep Talking and Nobody Explodes",
    "Keymasters Keep",
    "KH CoM",
    "KH RECoM",
    "KH: Birth by Sleep",
    "Kirby 64 - The Crystal Shards",
    "Kirby Super Star",
    "League of Legends",
    "Lil Gator Game",
    "Little Witch Nobeta",
    "Loonyland: Halloween Hill",
    "Luigi's Mansion",
    "Lunacid",
    "Majora's Mask",
    "Mario Kart 64",
    "Mario Kart: Double Dash",
    "Mega Man X",
    "Mega Man X2",
    "Mega Man X3",
    "MetroCUBEvania",
    "Metroid Fusion",
    "Metroid Zero Mission",
    "Minishoot' Adventures",
    "Minit",
    "Momodora: Moonlit Farewell",
    "Monster Sanctuary",
    "Nine Sols",
    "OpenRCT2",
    "Oracle of Ages",
    "Oracle of Seasons",
    "Ori and the Blind Forest",
    "Ori and the Will of the Wisps",
    "osu!",
    "Outer Wilds",
    "Oxygen Not Included",
    "Panel De Pon/Tetris Attack",
    "Paper Mario 64",
    "Paper Mario: The Thousand Year Door",
    "Pizza Tower",
    "Placid Plastic Duck Simulator",
    "Plateup!",
    "Pokemon Crystal",
    "Pokemon FRLG",
    "Pokemon Mystery Dungeon: EoS",
    "PokéPark Wii: Pikachu's Adventure [JP]",
    "Powerwash Simulator",
    "Prodigal",
    "Pseudoregalia",
    "Psychonauts",
    "Rabi-Ribi",
    "Rain World",
    "Ratchet & Clank 2",
    "Reventure",
    "Rift of the NecroDancer",
    "Rift Wizard",
    "Risk of Rain 2013",
    "Rogue Legacy",
    "Rusted Moss",
    "Satisfactory",
    "Scooby Doo No100F",
    "Sentinels of the multiverse",
    "Shadow the Hedgehog",
    "Sid Meier's Civilization V",
    "Simon Tatham's Portable Puzzle Collection",
    "Slay the Spire",
    "Sly 2: Band of Thieves",
    "Sly Cooper and the Thievius Racoonus",
    "SM Map Rando",
    "Sonic Adventure DX",
    "Sonic Heroes",
    "Sonic Riders",
    "Sonic Rush",
    "Sonic the Hedgehog",
    "Soulblazer",
    "Spelunker",
    "Spelunky 2",
    "Spinball: Pinball for Archipelago",
    "Spyro 3",
    "Stacklands",
    "Star Fox 64",
    "Star Wars: Episode1 Racer",
    "Stick Ranger",
    "Super Cat Planet",
    "Super Junkoid",
    "Super Mario Sunshine",
    "System Shock 2",
    "TCG Card Shop Simulator",
    "Tevi",
    "The Binding of Isaac Repentance",
    "The Legend of Zelda: Minish Cap",
    "The Legend of Zelda: Phantom Hourglass",
    "The Simpsons: Hit and Run",
    "The Sims 4",
    "Toejam & Earl",
    "Trackmania Random Campaign",
    "Turnip Boy Commits Tax Evasion",
    "Twilight Princess",
    "Ty the Tasmanian Tiger",
    "Tyrian",
    "UFO 50",
    "ULTRAKILL",
    "Wario Land",
    "Wario Land 4",
    "Watery Words",
    "Wordipelago",
    "XCOM 2: War of the Chosen",
    "Yooka-Laylee",
    "Yu-Gi-Oh! Dungeon Dice Monsters",
    "Yu-Gi-Oh! Forbidden Memories",
    "Yu-Gi-Oh! Ultimate Masters: WCT 2006",
    "Zelda 2: Adventure of Link",
    "Zork: Grand Inquistor",
    "ArchipIDLE",
];
