pub const VALID_GAMES: [&str; 288] = [
    "Adventure",
    "Aquaria",
    "Blasphemous",
    "Bomb Rush Cyberfunk",
    "Castlevania - Circle of the Moon",
    "Castlevania 64",
    "Celeste 64",
    "ChecksFinder",
    "Civilization VI",
    "Dark Souls III",
    "DLCQuest",
    "Donkey Kong Country 3",
    "DOOM 1993",
    "DOOM II",
    "Factorio",
    "Final Fantasy",
    "Final Fantasy Mystic Quest",
    "A Hat in Time",
    "Heretic",
    "Hollow Knight",
    "Hylics 2",
    "Inscryption",
    "Jak and Daxter: The Precursor Legacy",
    "Kingdom Hearts",
    "Kingdom Hearts 2",
    "Kirby's Dream Land 3",
    "Landstalker - The Treasures of King Nole",
    "The Legend of Zelda",
    "Lingo",
    "A Link to the Past",
    "Links Awakening DX",
    "Lufia II Ancient Cave",
    "Mario & Luigi Superstar Saga",
    "Mega Man 2",
    "MegaMan Battle Network 3",
    "Meritous",
    "The Messenger",
    "Muse Dash",
    "Noita",
    "Ocarina of Time",
    "Overcooked! 2",
    "Pokemon Emerald",
    "Pokemon Red and Blue",
    "Raft",
    "Risk of Rain 2",
    "Saving Princess",
    "Secret of Evermore",
    "shapez",
    "Shivers",
    "A Short Hike",
    "Sonic Adventure 2 Battle",
    "Starcraft 2",
    "Stardew Valley",
    "Subnautica",
    "Super Mario 64",
    "Super Mario Land 2",
    "Super Mario World",
    "Super Metroid",
    "Terraria",
    "Timespinner",
    "TUNIC",
    "Undertale",
    "VVVVVV",
    "Wargroove",
    "The Wind Waker",
    "The Witness",
    "Yacht Dice",
    "Yoshi's Island",
    "Yu-Gi-Oh! 2006",
    "Zillion",
    "A Link Between Worlds",
    "Against the Storm",
    "Air Delivery",
    "An Untitled Story",
    "ANIMAL WELL",
    "Anodyne",
    "Another Crabs Treasure",
    "APBingo",
    "Ape Escape 3",
    "Astalon",
    "Autopelago",
    "Balatro",
    "Banjo-Tooie",
    "Battle for Bikini Bottom",
    "Bomberman Hero",
    "Brotato",
    "Candy Box 2",
    "Castlevania - Harmony of Dissonance",
    "Symphony of the Night",
    "Cave Story",
    "Cavern of Dreams",
    "Celeste (Open World)",
    "Chrono Trigger Jets of Time",
    "Clique",
    "ClusterTruck",
    "Corn Kidz 64",
    "CrossCode",
    "Crystal Project",
    "Crystalis",
    "Dark Souls Remastered",
    "Dark Souls II",
    "Deep Rock Galactic",
    "Diddy Kong Racing",
    "Dome Keeper",
    "Donkey Kong Country 2",
    "DORONKO WANKO",
    "Dragon Warrior",
    "Duke Nukem 3D",
    "Dungeon Clawler",
    "EarthBound",
    "Ender Lilies",
    "Final Fantasy 12 Open World",
    "Final Fantasy Tactics A2",
    "Final Fantasy Tactics Advance",
    "Final Fantasy 6 Worlds Collide",
    "Final Fantasy XII Trial Mode",
    "Fire Emblem Sacred Stones",
    "Gauntlet Legends",
    "Getting Over It with Bennett Foddy",
    "Golden Sun The Lost Age",
    "Grim Dawn",
    "Guild Wars 2",
    "Hammerwatch",
    "Hatsune Miku Project Diva Mega Mix+",
    "Here Comes Niko!",
    "Iji",
    "Isles of the Sea and Sky",
    "Ittle Dew 2",
    "Jak and Daxter",
    "Jigsaw",
    "Paint",
    "Kabuto Park",
    "Keep Talking and Nobody Explodes",
    "Keymaster's Keep",
    "Kingdom Hearts Chain of Memories",
    "Kingdom Hearts RE Chain of Memories",
    "Kingdom Hearts Birth by Sleep",
    "Kirby 64 - The Crystal Shards",
    "Kirby Super Star",
    "League of Legends",
    "Lil Gator Game",
    "Little Witch Nobeta",
    "Loonyland",
    "Luigi's Mansion",
    "Lunacid",
    "Majora's Mask Recompiled",
    "Mario Kart 64",
    "Mario Kart: Double Dash",
    "Mega Man X",
    "Mega Man X2",
    "Mega Man X3",
    "MetroCUBEvania",
    "Metroid Fusion",
    "Metroid Zero Mission",
    "Minishoot Adventures",
    "Minit",
    "Momodora Moonlit Farewell",
    "Monster Sanctuary",
    "Nine Sols",
    "OpenRCT2",
    "The Legend of Zelda - Oracle of Ages",
    "The Legend of Zelda - Oracle of Seasons",
    "Ori and the Blind Forest",
    "Ori and the Will of the Wisps",
    "osu!",
    "Outer Wilds",
    "Oxygen Not Included",
    "Tetris Attack",
    "Paper Mario",
    "Paper Mario The Thousand Year Door",
    "Pizza Tower",
    "Placid Plastic Duck Simulator",
    "Pokemon Crystal",
    "Pokemon FireRed and LeafGreen",
    "Pokemon Mystery Dungeon Explorers of Sky",
    "PokePark",
    "Powerwash Simulator",
    "Prodigal",
    "Pseudoregalia",
    "Psychonauts",
    "Rabi-Ribi",
    "Rain World",
    "Ratchet & Clank 2",
    "Reventure",
    "Rift Wizard",
    "Rift Wizard",
    "Rogue Legacy",
    "Rusted Moss",
    "Satisfactory",
    "Scooby-Doo! Night of 100 Frights",
    "Sentinels of the Multiverse",
    "Shadow The Hedgehog",
    "Sid Meier's Civilization V",
    "Simon Tatham's Portable Puzzle Collection",
    "Slay the Spire",
    "Sly 2: Band of Thieves",
    "Sly Cooper and the Thievius Raccoonus",
    "Super Metroid Map Rando",
    "Sonic Adventure DX",
    "Sonic Heroes",
    "Sonic Riders",
    "Sonic Rush",
    "Sonic the Hedgehog 1",
    "Soul Blazer",
    "Spelunker",
    "Spelunky 2",
    "Spinball",
    "Spyro 3",
    "Stacklands",
    "Star Fox 64",
    "Star Wars Episode I Racer",
    "Stick Ranger",
    "Super Junkoid",
    "Super Mario Sunshine",
    "System Shock 2",
    "TCG Card Shop Simulator",
    "Tevi",
    "The Binding of Isaac Repentance",
    "The Minish Cap",
    "The Legend of Zelda - Phantom Hourglass",
    "The Simpsons Hit And Run",
    "The Sims 4",
    "Trackmania",
    "TurnipBoy",
    "Twilight Princess",
    "Ty the Tasmanian Tiger",
    "Tyrian",
    "UFO 50",
    "ULTRAKILL",
    "Wario Land",
    "Wario Land 4",
    "Watery Words",
    "Wordipelago",
    "XCOM 2 War of the Chosen",
    "Yu-Gi-Oh! Dungeon Dice Monsters",
    "Yu-Gi-Oh! Forbidden Memories",
    "Yu-Gi-Oh! Ultimate Masters: WCT 2006",
    "Zelda II: The Adventure of Link",
    "Zork Grand Inquisitor",
    "Cat Quest",
    "Digimon World",
    "Skyward Sword",
    "Bumper Stickers",
    "Archipelago",
    "Risk of Rain",
    "Ape Escape",
    "ChristmasDelivery",
    "Final Fantasy IV Free Enterprise",
    "Frogmonster",
    "Mario is Missing",
    "Sea of Thieves",
    "Severed Soul",
    "UFO 50",
    "Void Stranger",
    "Wargroove 2",
    "Haste",
    "Spyro the Dragon",
    "Cupheads",
    "Pokemon Pinball",
    "ActRaiser",
    "Archipela-Go",
    "Armored Core",
    "Axiom Verge",
    "Bomberman 64",
    "Brave Fencer Musashi",
    "Cassette Beasts",
    "Celeste",
    "Dark Cloud",
    "holo8",
    "Lego Star Wars: Complete Saga",
    "Lethal Company",
    "Lingo 2",
    "Mega Man 3",
    "Pokemon Black and White",
    "Pokemon Platinum",
    "Rift of the Necrodancer",
    "Twisty Cube",
    "Vampire Survivors",
    "Voltorb Flip",
    "Factorio Space Age Without Space",
    "Ship of Harkinian",
    "Signalis",
    "Super Smash Bros Melee",
    "Total War Warhammer 3",
    "Choo Choo Charles",
    "Bomberman The Second Attack",
    "Donkey Kong Country backwards",
    "ChecksMate",
];
