pub const VALID_GAMES: [&str; 294] = [
    "A Hat in Time",
    "A Link Between Worlds",
    "A Link to the Past",
    "A Short Hike",
    "ActRaiser",
    "Adventure",
    "Against the Storm",
    "Air Delivery",
    "An Untitled Story",
    "ANIMAL WELL",
    "Anodyne",
    "Another Crabs Treasure",
    "APBingo",
    "Ape Escape",
    "Ape Escape 3",
    "Aquaria",
    "Archipela-Go",
    "Archipelago",
    "Armored Core",
    "Astalon",
    "Autopelago",
    "Axiom Verge",
    "Balatro",
    "Banjo-Tooie",
    "Battle for Bikini Bottom",
    "Blasphemous",
    "Bomb Rush Cyberfunk",
    "Bomberman 64",
    "Bomberman Hero",
    "Bomberman The Second Attack",
    "Brave Fencer Musashi",
    "Brotato",
    "Bumper Stickers",
    "Candy Box 2",
    "Cassette Beasts",
    "Castlevania - Circle of the Moon",
    "Castlevania - Harmony of Dissonance",
    "Castlevania 64",
    "Cat Quest",
    "Cave Story",
    "Cavern of Dreams",
    "Celeste",
    "Celeste (Open World)",
    "Celeste 64",
    "ChecksFinder",
    "ChecksMate",
    "Choo Choo Charles",
    "ChristmasDelivery",
    "Chrono Trigger Jets of Time",
    "Civilization VI",
    "Clique",
    "ClusterTruck",
    "Corn Kidz 64",
    "CrossCode",
    "Crystal Project",
    "Crystalis",
    "Cuphead",
    "Dark Cloud",
    "Dark Souls II",
    "Dark Souls III",
    "Dark Souls Remastered",
    "Deep Rock Galactic",
    "Diddy Kong Racing",
    "Digimon World",
    "DLCQuest",
    "Dome Keeper",
    "Donkey Kong Country 2",
    "Donkey Kong Country 3",
    "Donkey Kong Country backwards",
    "DOOM 1993",
    "DOOM II",
    "DORONKO WANKO",
    "Dragon Warrior",
    "Duke Nukem 3D",
    "Dungeon Clawler",
    "EarthBound",
    "Ender Lilies",
    "Factorio",
    "Factorio Space Age Without Space",
    "Final Fantasy",
    "Final Fantasy 12 Open World",
    "Final Fantasy 6 Worlds Collide",
    "Final Fantasy IV Free Enterprise",
    "Final Fantasy Mystic Quest",
    "Final Fantasy Tactics A2",
    "Final Fantasy Tactics Advance",
    "Final Fantasy XII Trial Mode",
    "Fire Emblem Sacred Stones",
    "Frogmonster",
    "Gauntlet Legends",
    "Getting Over It",
    "Golden Sun The Lost Age",
    "Grim Dawn",
    "Guild Wars 2",
    "Hammerwatch",
    "Haste",
    "Hatsune Miku Project Diva Mega Mix+",
    "Here Comes Niko!",
    "Heretic",
    "Hollow Knight",
    "holo8",
    "Hylics 2",
    "Iji",
    "Inscryption",
    "Isles of the Sea and Sky",
    "Ittle Dew 2",
    "Jak and Daxter",
    "Jak and Daxter: The Precursor Legacy",
    "Jigsaw",
    "Kabuto Park",
    "Keep Talking and Nobody Explodes",
    "Keymaster's Keep",
    "Kingdom Hearts",
    "Kingdom Hearts 2",
    "Kingdom Hearts Birth by Sleep",
    "Kingdom Hearts Chain of Memories",
    "Kingdom Hearts RE Chain of Memories",
    "Kirby 64 - The Crystal Shards",
    "Kirby Super Star",
    "Kirby's Dream Land 3",
    "Landstalker - The Treasures of King Nole",
    "League of Legends",
    "Lego Star Wars: The Complete Saga",
    "Lethal Company",
    "Lil Gator Game",
    "Lingo",
    "Lingo 2",
    "Links Awakening DX",
    "Little Witch Nobeta",
    "Loonyland",
    "Lufia II Ancient Cave",
    "Luigi's Mansion",
    "Lunacid",
    "Majora's Mask Recompiled",
    "Mario & Luigi Superstar Saga",
    "Mario is Missing",
    "Mario Kart 64",
    "Mario Kart Double Dash",
    "Mega Man 2",
    "Mega Man 3",
    "Mega Man X",
    "Mega Man X2",
    "Mega Man X3",
    "MegaMan Battle Network 3",
    "Meritous",
    "MetroCUBEvania",
    "Metroid Fusion",
    "Metroid Zero Mission",
    "Minishoot Adventures",
    "Minit",
    "Momodora Moonlit Farewell",
    "Monster Sanctuary",
    "Muse Dash",
    "Nine Sols",
    "Noita",
    "Ocarina of Time",
    "OpenRCT2",
    "Ori and the Blind Forest",
    "Ori and the Will of the Wisps",
    "osu!",
    "Outer Wilds",
    "Overcooked! 2",
    "Paint",
    "Paper Mario",
    "Paper Mario The Thousand Year Door",
    "Pizza Tower",
    "Placid Plastic Duck Simulator",
    "Pokemon Black and White",
    "Pokemon Crystal",
    "Pokemon Emerald",
    "Pokemon FireRed and LeafGreen",
    "Pokemon Mystery Dungeon Explorers of Sky",
    "Pokemon Pinball",
    "Pokemon Platinum",
    "Pokemon Red and Blue",
    "PokePark",
    "Powerwash Simulator",
    "Prodigal",
    "Pseudoregalia",
    "Psychonauts",
    "Rabi-Ribi",
    "Raft",
    "Rain World",
    "Ratchet & Clank 2",
    "Reventure",
    "Rift of the Necrodancer",
    "Rift Wizard",
    "Rift Wizard",
    "Risk of Rain",
    "Risk of Rain 2",
    "Rogue Legacy",
    "Rusted Moss",
    "Satisfactory",
    "Saving Princess",
    "Scooby-Doo! Night of 100 Frights",
    "Sea of Thieves",
    "Secret of Evermore",
    "Sentinels of the Multiverse",
    "Severed Soul",
    "Shadow The Hedgehog",
    "shapez",
    "Ship of Harkinian",
    "Shivers",
    "Civilization V",
    "Signalis",
    "Simon Tatham's Portable Puzzle Collection",
    "Skyward Sword",
    "Slay the Spire",
    "Sly 2: Band of Thieves",
    "Sly Cooper and the Thievius Raccoonus",
    "Sonic Adventure 2 Battle",
    "Sonic Adventure DX",
    "Sonic Heroes",
    "Sonic Riders",
    "Sonic Rush",
    "Sonic the Hedgehog 1",
    "Soul Blazer",
    "Spelunker",
    "Spelunky 2",
    "Spinball",
    "Spyro 3",
    "Spyro the Dragon",
    "Stacklands",
    "Star Fox 64",
    "Star Wars Episode I Racer",
    "Starcraft 2",
    "Stardew Valley",
    "Stick Ranger",
    "Subnautica",
    "Super Junkoid",
    "Super Mario 64",
    "Super Mario Land 2",
    "Super Mario Sunshine",
    "Super Mario World",
    "Super Metroid",
    "Super Metroid Map Rando",
    "Super Smash Bros. Melee",
    "Symphony of the Night",
    "System Shock 2",
    "TCG Card Shop Simulator",
    "Terraria",
    "Tetris Attack",
    "Tevi",
    "The Binding of Isaac Repentance",
    "The Legend of Zelda",
    "The Legend of Zelda - Oracle of Ages",
    "The Legend of Zelda - Oracle of Seasons",
    "The Legend of Zelda - Phantom Hourglass",
    "The Messenger",
    "The Minish Cap",
    "The Simpsons Hit And Run",
    "The Sims 4",
    "The Wind Waker",
    "The Witness",
    "Timespinner",
    "Total War Warhammer 3",
    "Trackmania",
    "TUNIC",
    "TurnipBoy",
    "Twilight Princess",
    "Twisty Cube",
    "Ty the Tasmanian Tiger",
    "Tyrian",
    "UFO 50",
    "UFO 50",
    "ULTRAKILL",
    "Undertale",
    "Vampire Survivors",
    "Void Stranger",
    "Voltorb Flip",
    "VVVVVV",
    "Wargroove",
    "Wargroove 2",
    "Wario Land",
    "Wario Land 4",
    "Watery Words",
    "Wordipelago",
    "XCOM 2 War of the Chosen",
    "Yacht Dice",
    "Yoshi's Island",
    "Yu-Gi-Oh! 2006",
    "Yu-Gi-Oh! Dungeon Dice Monsters",
    "Yu-Gi-Oh! Forbidden Memories",
    "Yu-Gi-Oh! Ultimate Masters: WCT 2006",
    "Zelda II: The Adventure of Link",
    "Zillion",
    "Zork Grand Inquisitor",
    "APQuest",
    "CrosswordAP",
    "Factorio with Bob Mods",
    "Spyro 3",
    "TOEM",
    "Spicy Mycena Waffles",
    "Super Cat Planet",
];
