pub const VALID_GAMES: [&str; 352] = [
    "A Hat in Time",
    "A Link Between Worlds",
    "A Link to the Past",
    "A Short Hike",
    "Actraiser",
    "Against the Storm",
    "Air Delivery",
    "An Untitled Story",
    "ANIMAL WELL",
    "Anodyne",
    "Another Crabs Treasure",
    "AP Tombola",
    "APBingo",
    "Ape Escape",
    "Ape Escape 3",
    "APQuest",
    "Aquaria",
    "Archipela-Go",
    "Archipeladoku",
    "Archipelago",
    "Armored Core",
    "Astalon",
    "Autopelago",
    "Axiom Verge",
    "Baba is you",
    "Balatro",
    "Banjo-Tooie",
    "Battle for Bikini Bottom",
    "Bits & Bops",
    "BK Simulator",
    "Blasphemous",
    "Bomb Rush Cyberfunk",
    "Bomberman 64",
    "Bomberman Hero",
    "Bomberman The Second Attack",
    "Brave Fencer Musashi",
    "Brotato",
    "Bumper Stickers",
    "Candy Box 2",
    "Castlevania - Circle of the Moon",
    "Castlevania - Harmony of Dissonance",
    "Castlevania 64",
    "Castlevania: Dawn of Sorrow",
    "Cat Quest",
    "Cave Story",
    "Cavern of Dreams",
    "Celeste",
    "Celeste (Open World)",
    "Celeste 64",
    "ChecksFinder",
    "ChecksMate",
    "Choo Choo Charles",
    "ChristmasDelivery",
    "Chrono Trigger Jets of Time",
    "Civilization VI",
    "Clique",
    "ClusterTruck",
    "Corn Kidz 64",
    "Corru.Osberver",
    "CrossCode",
    "Crystal Project",
    "Crystalis",
    "Cuphead",
    "Dark Cloud",
    "Dark Souls II",
    "Dark Souls III",
    "Deep Rock Galactic",
    "Deltarune",
    "Diddy Kong Racing",
    "Digimon World",
    "DLCQuest",
    "Donkey Kong 64",
    "Donkey Kong Country 2",
    "Donkey Kong Country 3",
    "Donkey Kong Country backwards",
    "DOOM 1993",
    "DOOM II",
    "DORONKO WANKO",
    "Dracomino",
    "Dragon Warrior",
    "Dredge",
    "Duke Nukem 3D",
    "EarthBound",
    "Elementipelago",
    "Ender Lilies",
    "Factorio",
    "Factorio Bob's",
    "Factorio Space Age Without Space",
    "FEZ",
    "Final Fantasy",
    "Final Fantasy 12 Open World",
    "Final Fantasy 6 Worlds Collide",
    "Final Fantasy IV Free Enterprise",
    "Final Fantasy Mystic Quest",
    "Final Fantasy Tactics A2",
    "Final Fantasy Tactics Advance",
    "Final Fantasy XII Trial Mode",
    "Fire Emblem Sacred Stones",
    "Forged Curse",
    "Frogmonster",
    "Games",
    "Garfield Kart",
    "Gauntlet Legends",
    "Getting Over It",
    "Golden Sun The Lost Age",
    "Grim Dawn",
    "Hammerwatch",
    "Haste",
    "Hatsune Miku Project Diva Mega Mix+",
    "Here Comes Niko!",
    "Heretic",
    "Hollow Knight",
    "holo8",
    "Hylics 2",
    "I Was a Teenage Exocolonist",
    "Iji",
    "Inscryption",
    "Isles of the Sea and Sky",
    "Ittle Dew 2",
    "Jak and Daxter",
    "Jak and Daxter: The Precursor Legacy",
    "Jigsaw",
    "Kabuto Park",
    "Keep Talking and Nobody Explodes",
    "Keymaster's Keep",
    "Kingdom Hearts",
    "Kingdom Hearts 2",
    "Kingdom Hearts Birth by Sleep",
    "Kingdom Hearts Chain of Memories",
    "Kingdom Hearts RE Chain of Memories",
    "Kirby 64 - The Crystal Shards",
    "Kirby Super Star",
    "Kirby's Dream Land 3",
    "Landstalker - The Treasures of King Nole",
    "League of Legends",
    "Legend of Dragoon",
    "Lego Batman: The Video Game",
    "Lego Star Wars: The Complete Saga",
    "Lethal Company",
    "Lingo",
    "Lingo 2",
    "Links Awakening DX",
    "Little Witch Nobeta",
    "Loonyland",
    "Lufia II Ancient Cave",
    "Luigi's Mansion",
    "Lunacid",
    "Mario & Luigi Superstar Saga",
    "Mario is Missing",
    "Mario Kart 64",
    "Mario Kart Double Dash",
    "Mario Kart Wii",
    "Mega Man 2",
    "Mega Man 3",
    "Mega Man X",
    "Mega Man X2",
    "Mega Man X3",
    "MegaMan Battle Network 3",
    "Meritous",
    "MetroCUBEvania",
    "Metroid Fusion",
    "Metroid: Zero Mission",
    "Minecraft",
    "Minecraft Dig",
    "Minishoot Adventures",
    "Minit",
    "Momodora Moonlit Farewell",
    "Monster Sanctuary",
    "Muse Dash",
    "Nine Sols",
    "Noita",
    "Nonograhmm",
    "Ocarina of Time",
    "OpenRCT2",
    "Ori and the Blind Forest",
    "Ori and the Will of the Wisps",
    "Ori and the Will of the Wisps",
    "osu!",
    "Outer Wilds",
    "Overcooked! 2",
    "Paint",
    "Paper Mario",
    "Paper Mario The Thousand Year Door",
    "Peggle Deluxe",
    "Peggle Nights",
    "Pizza Tower",
    "Placid Plastic Duck Simulator",
    "Plants vs Zombies Replanted",
    "Plok",
    "Pokemon Black and White",
    "Pokemon Crystal",
    "Pokemon Emerald",
    "Pokemon FireRed and LeafGreen",
    "Pokemon Mystery Dungeon Explorers of Sky",
    "Pokemon Pinball",
    "Pokemon Platinum",
    "Pokemon Ranger (Quest)",
    "Pokemon Red and Blue",
    "Pokemon Stadium",
    "PokePark",
    "Pokepelago",
    "Portal 2",
    "Powerwash Simulator",
    "Prodigal",
    "Pseudoregalia",
    "Psychonauts",
    "Rabbit and Steel",
    "Rabi-Ribi",
    "Raft",
    "Rain World",
    "Ratchet & Clank 2",
    "Refunct",
    "Reventure",
    "Rift of the Necrodancer",
    "Rift Wizard",
    "Rift Wizard",
    "Risk of Rain",
    "Risk of Rain 2",
    "Rogue Legacy",
    "Rusted Moss",
    "Satisfactory",
    "Saving Princess",
    "Scooby-Doo! Night of 100 Frights",
    "Secret of Evermore",
    "Sentinels of the Multiverse",
    "Severed Soul",
    "Shadow The Hedgehog",
    "shapez",
    "shapez 2",
    "Ship of Harkinian",
    "Shivers",
    "Signalis",
    "Simon Tatham's Portable Puzzle Collection",
    "Skyward Sword",
    "Slay the Spire",
    "Slime Rancher",
    "Sly 2: Band of Thieves",
    "Sly Cooper and the Thievius Raccoonus",
    "Sonic Advance 2",
    "Sonic Adventure 2 Battle",
    "Sonic Adventure DX",
    "Sonic Heroes",
    "Sonic Riders",
    "Sonic Rush",
    "Sonic the Hedgehog 1",
    "Soul Blazer",
    "Spelunker",
    "Spelunky 2",
    "Spicy Mycena Waffles",
    "Spinball",
    "Spyro 2",
    "Spyro 3",
    "Spyro 3",
    "Spyro the Dragon",
    "Stacklands",
    "Star Fox 64",
    "Star Wars Episode I Racer",
    "Starcraft 2",
    "Stardew Valley",
    "Stick Ranger",
    "Streets of Rage",
    "Subnautica",
    "Subspace Emissary",
    "Super Cat Planet",
    "Super Junkoid",
    "Super Mario 64",
    "Super Mario Land 2",
    "Super Mario Sunshine",
    "Super Mario World",
    "Super Metroid",
    "Super Metroid Map Rando",
    "Super Smash Bros. Melee",
    "Symphony of the Night",
    "System Shock 2",
    "TCG Card Shop Simulator",
    "Terraria",
    "Tetris (GB)",
    "Tetris Attack",
    "Tevi",
    "The Binding of Isaac Repentance",
    "The Grinch",
    "The Legend of Zelda",
    "The Legend of Zelda - Oracle of Ages",
    "The Legend of Zelda - Oracle of Seasons",
    "The Legend of Zelda - Phantom Hourglass",
    "The Messenger",
    "The Minish Cap",
    "The Simpsons Hit And Run",
    "The Wind Waker",
    "The Witness",
    "Timespinner",
    "TOEM: A Photo Adventure",
    "Total War Warhammer 3",
    "Trackmania",
    "TUNIC",
    "TurnipBoy",
    "Twilight Princess",
    "Twisty Cube",
    "Ty the Tasmanian Tiger",
    "Tyrian",
    "UFO 50",
    "UFO 50",
    "ULTRAKILL",
    "UNBEATABLE Arcade",
    "Undertale",
    "Unfair Flips",
    "Untitled Goose Game",
    "uzDOOM",
    "Vampire Survivors",
    "Void Stranger",
    "Voltorb Flip",
    "VVVVVV",
    "Wargroove",
    "Wargroove 2",
    "Wario Land",
    "Wario Land 4",
    "Watery Words",
    "West of Loathing",
    "Wordipelago",
    "XCOM 2 War of the Chosen",
    "Yacht Dice",
    "Yacht Dice Bliss",
    "Yoshi's Island",
    "Yu-Gi-Oh! 2006",
    "Yu-Gi-Oh! Dungeon Dice Monsters",
    "Yu-Gi-Oh! Forbidden Memories",
    "Yu-Gi-Oh! Ultimate Masters: WCT 2006",
    "Zelda II: The Adventure of Link",
    "Zillion",
    "Zork Grand Inquisitor",
    "BKBK But It's Only Furnace Fun",
    "Yellow Taxi Goes Vroom",
    "Cobalt Core",
    "Donkey Kong Country 1",
    "Donkey Kong Toluca",
    "La-Mulana 2",
    "Minecraft Fabric",
    "Hungry Pumpkin",
    "Peak",
    "Castlevania: Portrait of Ruin",
    "Legend of Zelda: A Link to the Past OWR",
    "Kingdom Hearts Dream Drop Distance",
    "Gato Roboto B-Side",
    "HI-FI Rush",
    "Mega Man X4",
    "Ys VIII: Lacrimosa of Dana",
    "Burnout 3",
    "RACCOIN: Coin Pusher Roguelike",
    "Cloverpit",
    "Librarian: Tidy up the arcane Library",
    "Cookie Clicker",
    "Mega Man 1",
];
